### ISSUE TITLE
macOS does not have link.h

### ISSUE THREAD

**Issue by barracuda156** [LLNL/GOTCHA#121]
```
In file included from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_gotcha/gotcha/work/GOTCHA-1.0.4/src/translations.h:21,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_gotcha/gotcha/work/GOTCHA-1.0.4/src/gotcha.c:16:
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_gotcha/gotcha/work/GOTCHA-1.0.4/include/gotcha/gotcha.h:34:10: fatal error: link.h: No such file or directory
   34 | #include <link.h>
      |          ^~~~~~~~
compilation terminated.
```

See related: https://github.com/geodynamics/aspect/issues/218

**Comment by barracuda156** [comment]
And also elf.h, obviously:
```
In file included from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_gotcha/gotcha/work/GOTCHA-1.0.4/src/gotcha_utils.c:16:
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_gotcha/gotcha/work/GOTCHA-1.0.4/src/gotcha_utils.h:36:10: fatal error: elf.h: No such file or directory
   36 | #include <elf.h>
      |          ^~~~~~~
compilation terminated.
```

**Comment by barracuda156** [comment]
(Or if there is no intention to support anything but Linux, perhaps worth stating it clearly in README.)

**Comment by hariharan-devarajan** [comment]
@barracuda156 Yes we only support Linux currently. I am in the process of updating our documentation. I will include this. Thanks for pointing this out.

**Comment by hariharan-devarajan** [comment]
@barracuda156 I have this updated in [here](https://gotcha--125.org.readthedocs.build/en/125/limitations.html#operating-system-support). Do you think I should add any other things related to this issue?

**Comment by barracuda156** [comment]
@hariharan-devarajan Thank you. Does it work on FreeBSD by the way? It uses ELF, AFAIK, but I have no environment to test.

**Comment by hariharan-devarajan** [comment]
I havent tested it on that either. I currently don't have the bandwidth. But if you end up trying, I would be happy to add it to the documentation. 

If you agree I will close this issue.

**Comment by barracuda156** [comment]
Yes, let us close this. Thank you.
