### ISSUE TITLE
Please provide GOTCHA version in header

### ISSUE THREAD

**Issue by bertwesarg** [LLNL/GOTCHA#149]
The source version, not the library interface version (aka libtool version). Thanks.

**Comment by hariharan-devarajan** [comment]
Do u mean macro definitions for Major Minor and revision of source? 

Something like

#define GOTCHA_MAJOR_VERSION 1

and so on?

If so sure, i can generate it for the installation.

**Comment by bertwesarg** [comment]
exactly. To integrate #148 into our build system, I need to check the version. For versions <=1.0.6 I will keep `libOpenCL.so` in our filter list.

**Comment by hariharan-devarajan** [comment]
@bertwesarg Ok, I added a PR for this #150.

[docs](https://gotcha--150.org.readthedocs.build/en/150/api.html#using-gotcha-version-macros) show how to use them. 

This uses boost style version checking so that u can do something like this

```
#if GOTCHA_VERSION >= GOTCHA_GET_VERSION(1,0,6)
...
#endif
```
