### ISSUE TITLE
End-to-end Testing

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/GOTCHA#16]
Right now we have the following tests

1. Minimal (wrap a symbol, call it)
2. dlopen (fails)
3. A unit test suite

Obvious todo's

1. Stacking

What else do we need?

**Comment by mplegendre** [comment]
I have an incoming hammer test, will submit a PR latter this morning if CMake start cooperating.  Gotcha seems to be working well under the heavy load it creates.

**Comment by DavidPoliakoff** [comment]
Hm, let me know if the CMake side of it is bad, that's something I'm typically good at fixing.

**Comment by DavidPoliakoff** [comment]
We at least have a test for this in the stacking PR, and the hammer tests are in. I'm going to declare this good for 0.1
