### ISSUE TITLE
Error Handling interface

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/GOTCHA#20]
@mplegendre : usual "this can be reassigned to me" rules apply, I'll stop prefixing issues with this.

Right now if things go wrong, users will be aware in only a limited sense. We need to think about what users might want to know about their calls into GOTCHA, how they might want to ask for it, and provide them with useful info. I won't prejudice you with designs in advance.

**Comment by mplegendre** [comment]
Can do, though I'm about to head out on travel for the next ~1.5 weeks, so it won't happen immediately.
