### ISSUE TITLE
Add User Manual

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/GOTCHA#43]
Right now we have minimal API documentation, and some examples. A more in-depth guide to the functionality of Gotcha would be beneficial, especially as things like the configuration interface come online

**Comment by mplegendre** [comment]
I'll start putting together framework for a user's guide.  What's our preferred format?  I'm tempted to keep it simple with MS Word that we export to PDF before releases.

**Comment by DavidPoliakoff** [comment]
Would you be opposed to doing something Sphinx-like? I quite like what Spack does, they have a site on [ReadTheDocs](https://spack.readthedocs.io/en/latest/), which gets exported to a [PDF](https://media.readthedocs.org/pdf/spack/latest/spack.pdf) (warning: PDF link).

They have a [user guide](https://docs.readthedocs.io/en/latest/getting_started.html) which is pretty innocuous. Obviously I'm flexible, but if we want the best end result, that's my recommendation.

**Comment by DavidPoliakoff** [comment]
Just talked with @tgamblin , who mentioned that a BLT build may buy us some documentation stuff for free, and that ReadTheDocs is how a lot of the LLNL codes are going, so using it would put us in line with people's expectations
