### ISSUE TITLE
Adding C++ support

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/GOTCHA#47]
I plan on using this as a meta-issue from which we track C++ development in Gotcha.

First up is #46 : it would be good to have C++ niceness available to our users who would like it.

Some broader issues/philosophy on C++ in Gotcha:

1. Never ever ever any C++ compiled code in the Gotcha library. Ever

1. Name mangling is a thing in C++, we need to not get ourselves in trouble with it, and possibly want facilities to support it

1. C++ objects have lifetimes, if they contain function pointers which Gotcha binds to and which then get deleted/freed, we are in trouble. Careful consideration of object lifetimes will be necessary for safe interfaces, especially considering things like "free" getting called after a gotcha binding to free gets freed

**Comment by mplegendre** [comment]
Let's low-priority #46, as we don't need it for the "Release 0.1" project.

I'd suggest we finish designing the C interface changes in #44 and #45, get the 0.1 release out, then use the subsequent release for this C++ and other efforts.
