### ISSUE TITLE
Make types match gotcha documentation

### ISSUE THREAD

**Issue by mplegendre** [LLNL/GOTCHA#61]
I'm working on the gotcha documentation, and writing the types as they will be.  We'll need to modify the gotcha source to match.

Specifically, gotcha_binding_t should be:

typedef struct {
  const char *name;
  void *wrapper_pointer;
  gotcha_wrappee_handle_t function_handle;
} gotcha_binding_t;

and gotcha_error_t:

typedef enum {
  ...
} gotcha_error_t;

**Comment by mplegendre** [comment]
@DavidPoliakoff, I'm looking at the gotcha source, and this issue wasn't done.  There's still a opaque_handle in the gotcha_binding_t.  Also function_handle should have been a pointer to a gotcha_wrappee_t.

**Comment by DavidPoliakoff** [comment]
@mplegendre : what's a gotcha_wrappee_t? It's a gotcha_wrappee_handle_t (currently a void*). Fixing the opaque thing now

**Comment by mplegendre** [comment]
Sorry, I meant the gotcha_wrappee_handle_t in the gotcha_binding_t tables should be a gotcha_wrappee_handle_t*.  Everything's still compiling because it's a void* typedef, but we're asking the user to pass a pointer to a gotcha_wrappee_handle_t.
