### ISSUE TITLE
unable to wrap functions in an init constructor

### ISSUE THREAD

**Issue by mwkrentel** [LLNL/GOTCHA#83]
Is it possible to wrap a function in an init constructor?  I've tried
a couple things and I can wrap a function, but I can't get it to apply
in another library's init ctor.

(1) The "pure gotcha" attempt.

I tried to wrap 'sigprocmask' (it's part of a cycle of deadlock
involving tcmalloc, libunwind and libmonitor, but that's another
story).

I created a shared library `libmygotcha.so` containing:

```
typedef int (* sigprocmask_fptr) (int, void *, void *);

static gotcha_wrappee_handle_t sigprocmask_handle;

static sigprocmask_fptr real_sigprocmask;

static int
sigprocmask_wrap(int how, void * set, void * old_set)
{
    ...
}

static gotcha_binding_t bindings [] = {
    { "sigprocmask", sigprocmask_wrap, &sigprocmask_handle },
};

void __attribute__ ((constructor))
monitor_init_ctor(void)
{
    gotcha_wrap(bindings, 1, "mymonitor");
    real_sigprocmask = (sigprocmask_fptr) gotcha_get_wrappee(sigprocmask_handle);
}
```

Put the above into a shared library and LD_PRELOAD it.  Run an app
that uses its own shared library and calls sigprocmask from both the
main program and the init ctor for a shared library.

I can tell that the above code gets run, and indeed it wraps
sigprocmask after main, but not in the library's init ctor.

Ok, so maybe it's a matter of timing.  There are two init ctors in
play, if the other one gets run first, then maybe the wrapping happens
too late.

----------

(2) The "hybrid" attempt.

Override __libc_start_main by the traditional LD_PRELOAD and
dlsym(RTLD_NEXT) method.  (This is what libmonitor does for the
dynamic case.)

Run gotcha_wrap from inside the __libc_start_main override.  Same
result.  The wrapping happens and applies after main, but not in the
init ctor.

The hope was that by wrapping __libc_start_main maybe the gotcha
wrapping happens before the init ctor.  But no.

----------

So, is there a way to call gotcha_wrap where it will happen before
init constructors?

The traditional LD_PRELOAD and dlsym(RTLD_NEXT) will do this.

This is important for hpctoolkit.  There are libraries that start
pthreads (and other functions) inside init constructors and we need to
catch them.

ping @mplegendre and @DavidPoliakoff

**Comment by mwkrentel** [comment]
Yup, it is a timing problem in startup.  With a little more debug
output, I can see that the application init ctor is run before my
preloaded gotcha init ctor.  That's why the wrapping didn't happen.
Not exactly what I'd call "pre".

It also seems that the init constructors are run before
__libc_start_main, so my hybrid solution of overriding start main
isn't going to help.  (I had hoped and kinda thought that start main
was run first.)

So, I'm stuck.  Is there some other way to run gotcha_wrap sooner?
Can you impose an order on init constructors to run mine first?

If not, then gotcha is fundamentally blind to init constructors.

**Comment by mplegendre** [comment]
As you deduced, you wouldn't be able to reliably wrap functions in library constructors.

**Comment by mwkrentel** [comment]
@mplegendre If you're going to close the issue because this can't be
fixed, and it probably can't, then you should at least put something
in the docs that identifies this as a fundamental limitation.
