### ISSUE TITLE
Different behavior using GCC or ICC

### ISSUE THREAD

**Issue by hbrunie** [LLNL/GOTCHA#87]
Hello,

I am using gotcha to capture exp math function calls (thanks for the tool by the way ;) ),
but even if the exp calls appears in both g++ and icpc compiled binary (I looked into with objdump -D), the former is correctly intercepted whereas the latter is not ...

Would you have any explanation of this difference? They are both compiled in O0.
Thanks

**Comment by hbrunie** [comment]
I think the issue is that libm might be embedded in the binary with icpc, thus no more dynamic look up.

**Comment by jrmadsen** [comment]
@mplegendre This is quite possibly the same issue that I emailed you and @DavidPoliakoff about.

**Comment by jrmadsen** [comment]
Oh wait, nevermind. `exp` was fine -- it was `cos` that was returning the wrong answer.

**Comment by jrmadsen** [comment]
@hbrunie run with `GOTCHA_DEBUG=2` and you will see if the log about which functions are successfully wrapped

**Comment by jrmadsen** [comment]
This was the list of issues I found with the C math library and the GCC compiler:

- `double exp(double)`
  - works 
- `float expf(float)`
  - returns it's argument as the answer
- `double cos(double)`
  - returns it’s argument as the answer 
- `float cosf(float)`
  - returns its argument as the answer

**Comment by hbrunie** [comment]
Thanks Jonathan,

indeed the symbols are all in text with INTEL compiler:
0000000000a670a0 T __exp10q
0000000000a67130 T __exp2q
0000000000a671c0 T __expq
0000000000ad15f0 T __frexpq
0000000000ad1890 T __ldexpq
0000000000a67970 T cexp
0000000000a67990 T cexp10
0000000000a67980 T cexp10f
0000000000a73360 T cexpf
0000000000a67ad0 T exp
0000000000a67ae0 T exp10
0000000000a67af0 T exp10f
0000000000a67b00 T expf
0000000000a67b80 T frexp
0000000000a67b90 T frexpf
0000000000a67c00 T ldexp

Thus this is not a GOTCHA issue.
